name: fast_mctd_mor
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip>=23.0
  
  # PyTorch with CUDA support
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=2.0.0
  - pytorch-cuda=11.8
  
  # Core Scientific Computing
  - numpy>=1.24.0
  - scipy>=1.10.0
  - scikit-learn>=1.2.0
  - pandas>=2.0.0
  
  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.14.0
  - pillow>=9.5.0
  
  # System utilities
  - psutil>=5.9.0
  - h5py>=3.8.0
  
  # Development
  - jupyter>=1.0.0
  - ipykernel>=6.23.0
  - pytest>=7.3.0
  
  # Code quality
  - black>=23.3.0
  - isort>=5.12.0
  
  # GPU monitoring
  - gpustat
  - nvidia-ml-py
  
  # pip dependencies (packages not available in conda)
  - pip:
    - torch-summary>=1.4.5
    - torch-optimizer>=0.3.0
    - einops>=0.6.0
    - timm>=0.9.0
    - tqdm>=4.65.0
    - rich>=13.3.0
    - wandb>=0.15.0
    - tensorboard>=2.13.0
    - lpips>=0.1.4
    - pytorch-fid>=0.3.0
    - clean-fid>=0.1.35
    - accelerate>=0.20.0
    - xformers>=0.0.20
    - transformers>=4.30.0
    - diffusers>=0.17.0
    - omegaconf>=2.3.0
    - hydra-core>=1.3.0
    - opencv-python>=4.7.0
    - imageio>=2.28.0
    - memory-profiler>=0.60.0
    - line-profiler>=4.0.0
    - faiss-cpu>=1.7.4
    - datasets>=2.12.0
    - librosa>=0.10.0
    - numba>=0.57.0
    - sympy>=1.12.0
    - networkx>=3.1.0
    - astropy>=5.3.0
